name: Debug Oblivion Install

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ellenőrzés
        run: echo "Workflow működik!"

      - name: Operációs rendszer információk
        run: uname -a

      - name: Alapvető csomagok frissítése
        run: sudo apt update && sudo apt install -y curl

      - name: Curl teszt
        run: curl --version
