name: Debug Oblivion Install

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ellenőrzés
        run: echo "Workflow működik!"

      - name: Operációs rendszer információk
        run: uname -a

      - name: Alapvető csomagok frissítése
        run: sudo apt update && sudo apt install -y curl

      - name: Curl teszt
        run: curl --version

      - name: Telepítő script letöltése
        run: curl -sL https://raw.githubusercontent.com/OblivionUser/oblivion_web_installer/main/install.sh -o install.sh

      - name: Ellenőrizzük, hogy a fájl letöltődött-e
        run: ls -lah install.sh

      - name: Nézzük meg a fájl tartalmát
        run: cat install.sh

      - name: Ellenőrizzük a fájl futtathatóságát
        run: file install.sh

      - name: Script végrehajtása
        run: |
          chmod +x install.sh
          ./install.sh
