name: Oblivion Web Install

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Telepítési környezet előkészítése
        run: |
          sudo apt update
          sudo apt install -y curl

      - name: Letöltés és telepítés
        run: |
          curl -sL https://raw.githubusercontent.com/OblivionUser/oblivion_web_installer/main/install.sh -o install.sh
          chmod +x install.sh
          ./install.sh
